### ISSUE TITLE
第1部分和第2部分的9个勘误

### ISSUE THREAD

**Issue by joymufeng** [ReactivePlatform/Reactive-Design-Patterns#139]
#### 页码
78

#### 原文
`套接口`上有数据可用

#### 修正
`套接字`上有数据可用

#### 说明
应与前文翻译保持一致。

--- 

#### 页码
85

#### 原文
当你将`指针`悬停在电子邮件的发件人上方时

#### 修正
当你将`鼠标`悬停在电子邮件的发件人上方时

#### 说明
应与前文翻译保持一致。

--- 

#### 页码
98

#### 原文
用测试存根代码来替换掉层级结构中的同级、`子代`以及上级模块。

#### 修正
用测试存根代码来替换掉层级结构中的同级、`下级`以及上级模块。

#### 说明
翻译应与上下文保持一致。

--- 

#### 页码
98

#### 原文
可将它们`被部署`到

#### 修正
可将它们`部署`到

#### 说明
typo

--- 

#### 页码
112

#### 原文
在Gmail`在`例子中，

#### 修正
在Gmail例子中，

#### 说明
typo

--- 

#### 页码
114

#### 原文
这导致了添加组件结构的新方面`;`

#### 修正
这导致了添加组件结构的新方面`:`

#### 说明
typo

--- 

#### 页码
119

#### 原文
`空白`们的执行顺序

#### 修正
们的执行顺序

#### 说明
排版错误，行首有多余空白。

--- 

#### 页码
123

#### 原文
都尽快地把它`向前`推送给下一站

#### 修正
都尽快地把它`向后`推送给下一站

#### 说明
typo

--- 

#### 页码
125

#### 原文
后一种形式，我们将竭力保持推论的技术性，而`以前的形式`却允许我们

#### 修正
后一种形式，我们将竭力保持推论的技术性，而`前一种形式`却允许我们

#### 说明
应与上一句相呼应。

---

**Comment by hepin1989** [comment]
鼠标 -> 鼠标指针

**Comment by hepin1989** [comment]
鼠标 -> 鼠标指针

**Comment by hepin1989** [comment]
done
