### ISSUE TITLE
appendix C, The Reactive Manifesto

### ISSUE THREAD

**Issue by hepin1989** [ReactivePlatform/Reactive-Design-Patterns#21]
目前书中的附录C附带了这部分内容:

1. [ ] 看是否需要更新到最新的反应式宣言
2. [ ] 目前的中文翻译是 `响应式宣言` ,可以联系Chinese版本的原作者,我们看下如何统一,还需要提交PR
3. [ ] 翻译这部分内容,并且合并到 https://github.com/reactivemanifesto/reactivemanifesto
4. [ ] 书中最终定稿的版本,需要感谢 @pimgeek

**Comment by hepin1989** [comment]
@pimgeek @Hawstein @scweang @cjuexuan 
我们需要统一这个`The Reactive Manifesto`的中文译本.

**Comment by pimgeek** [comment]
请问需要我做什么呢？我不太了解当前这个版本库的上下文，是为了出版一本在线电子书吗？是否希望规范概念的名称？

**Comment by hepin1989** [comment]
@pimgeek 亲,是这样的,目前这个代码库是用来追踪我们对于`Reactive Design Patterns`这本书的中文版翻译的.

我们具体的翻译是在Google Docs进行的,因为`The Reactive Manifesto`是您第一个翻译的,所以为了尊重版权,这块儿肯定要找您看一下呢.同时因为书中最后的附录C,也就是这里的上下文,也是附带了的,所以

我期待做下面的事情:

1.  我们规范下`Reactive System`等这样的`Reactive`的中文译法,我个人觉得`响应式`不对,而应该是`反应式`. 
2. 我们需要统一`The Reactive Manifesto`,既和您达成一致,我们提供`The Reactive Manifesto`的中译版本.
3. 书中附录C中需要直接引入这部分内容,所以需要感谢您:)

所以您看如何呢?

如果您觉得没有问题,那么我后面可能会去对那个`The Reactive Manifesto`进行PR,然后还请您Review呢.当我们大家达成一致,并且最后合并后,书中也会采用这部分内容,原封不动的.当然也会感谢您的付出:).

**Comment by pimgeek** [comment]
@hepin1989 请参考一下这里的讨论，@ben7th 是共同译者，他对“响应式”这个说法有更深的思考。
https://github.com/reactivemanifesto/reactivemanifesto/pull/74#discussion_r55496875

**Comment by hepin1989** [comment]
@zhan-ge CC
