### ISSUE TITLE
constraint & term

### ISSUE THREAD

**Issue by hepin1989** [ReactivePlatform/Reactive-Design-Patterns#27]
记录翻译标准术语

[ ] resilient &  resilience -> 韧性 / 回弹性
[ ] programming constructs -> 编程构造？

**Comment by hepin1989** [comment]
@Hawstein @scweang 

请把我们发现的一些术语贴在这里,然后我们合计下,
并确定出最终的译法,全局统一吧.

**Comment by scweang** [comment]
Simple Component Pattern
简单组件模式

**Comment by scweang** [comment]
Error Kernel pattern

**Comment by scweang** [comment]
Let-It-Crash pattern

**Comment by mumutu** [comment]
Let-It-Crash 还是不翻译吧 直接引用好了。"Let-it-Crash"

**Comment by hepin1989** [comment]
放任崩溃
